# Generated by Django 3.2.6 on 2021-08-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0003_remove_symptoms_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symptoms',
            new_name='Symptom',
        ),
    ]
