# Generated by Django 3.2.6 on 2021-08-09 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0004_rename_symptoms_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comorbidity', models.CharField(max_length=50)),
                ('prescription', models.TextField(max_length=500)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
            ],
        ),
    ]
