# Generated by Django 3.2.6 on 2021-08-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0006_alter_symptom_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='patient',
        ),
        migrations.AddField(
            model_name='symptom',
            name='patients',
            field=models.ManyToManyField(to='screening.Patient'),
        ),
    ]
