# Generated by Django 3.2.6 on 2021-08-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0007_auto_20210811_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='patients',
            field=models.ManyToManyField(blank=True, to='screening.Patient'),
        ),
        migrations.CreateModel(
            name='SymptomPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.patient')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screening.symptom')),
            ],
        ),
    ]
