# Generated by Django 3.2.6 on 2021-08-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0008_auto_20210811_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='patients',
        ),
    ]
