# Generated by Django 3.2.6 on 2021-08-18 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0009_remove_symptom_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='active_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
